import antfu from '@antfu/eslint-config'

const OFF = 0
const WARN = 1
const ERROR = 2

export default antfu({
  ignores: [
    'public',
    'build',
    'dist',
    'node_modules',
    'coverage',
    'src/assets/**',
    // Auto-generated by Next.js on every dev/build run.
    'next-env.d.ts',
  ],
  stylistic: {
    indent: 2,
    quotes: 'single',
    overrides: {
      'antfu/top-level-function': 'off',
      'style/arrow-parens': 'off',
      curly: 'off',
    },
  },
  jsonc: true,
  formatters: {
    markdown: true,
  },
  typescript: true,
  react: true,
  // Replaces the legacy `extends: ['next/core-web-vitals']`, which is not
  // supported by flat config and was silently ignored.
  nextjs: true,
  markdown: true,
  rules: {
    'antfu/top-level-function': OFF,

    // Rule names follow `@eslint-react/eslint-plugin` v5, where the former
    // `react-dom/*`, `react-hooks/*` and `react-hooks-extra/*` namespaces are
    // flattened into the `react/*` namespace.
    'react/dom-no-unsafe-target-blank': OFF,
    'react/dom-no-missing-button-type': OFF,
    'react/dom-no-dangerously-set-innerhtml': OFF,
    'react/jsx-no-useless-fragment': OFF,
    'react/jsx-no-comment-textnodes': OFF,
    'react/no-array-index-key': OFF,
    'react/no-unnecessary-use-prefix': OFF,
    'react/rules-of-hooks': OFF,
    'react/exhaustive-deps': WARN,
    'react-refresh/only-export-components': OFF,

    'unused-imports/no-unused-vars': WARN,
    curly: [ERROR, 'multi-line', 'consistent'],

    'no-multiple-empty-lines': [
      ERROR,
      {
        max: 3,
      },
    ],
    'no-console': WARN,

    'style/jsx-self-closing-comp': [ERROR, {
      component: true,
      html: false,
    }],
    'style/no-multiple-empty-lines': [ERROR, {
      max: 2,
      maxEOF: 0,
    }],
    'style/max-statements-per-line': ERROR,
    'style/quote-props': [ERROR, 'as-needed'],

    'ts/no-use-before-define': OFF,
    'ts/ban-ts-comment': OFF,
  },
})
